---

- name: Start time services
  service: name=systemd-timesyncd state=started enabled=yes
  become: yes
  ignore_errors: yes

- name: Run timedatectl status
  command: /usr/bin/timedatectl status
  changed_when: False
  check_mode: no
  register: timedatectl_result

- name: Copy timesyncd config
  copy: src=timesyncd.conf dest=/etc/systemd/timesyncd.conf
  become: yes

- name: Set timezone
  command: /usr/bin/timedatectl set-timezone Asia/Jakarta
  when: "'Europe/Zurich' not in timedatectl_result.stdout"
  become: yes

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'Network time on: no' in timedatectl_result.stdout"
  become: yes

# add newline because locale-gen doesn't work without
- name: Specify locale
  copy: content="en_US.UTF-8 UTF-8\n" dest=/etc/locale.gen
  become: yes
  register: locale

- name: Generate locale
  shell: locale-gen
  become: yes
  when: locale.changed

- name: Set locale
  copy: content="LANG=en_US.UTF-8" dest=/etc/locale.conf
  become: yes

